In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("adult23.csv")

In [8]:
print(df.shape)

(29522, 647)

In [9]:
df.head()

,URBRRL,RATCAT_A,INCTCFLG_A,IMPINCFLG_A,LANGSPECR_A,LANGSOC_A,LANGDOC_A,LANGMED_A,LANGHM_A,PPSU,...,PROXYREL_A,PROXY_A,AVAIL_A,HHSTAT_A,INTV_MON,RECTYPE,IMPNUM_A,WTFA_A,HHX,POVRATTC_A
0,3,4,0,0,NaN,NaN,NaN,NaN,NaN,2,...,NaN,NaN,1,1,1,10,1,7371.139,H029691,1.01
1,4,8,0,0,NaN,NaN,NaN,NaN,NaN,2,...,NaN,NaN,1,1,1,10,1,3146.794,H028812,2.49
2,4,14,0,0,NaN,NaN,NaN,NaN,NaN,2,...,NaN,NaN,1,1,1,10,1,10807.558,H045277,6.73
3,4,10,0,0,NaN,NaN,NaN,NaN,NaN,2,...,NaN,NaN,1,1,1,10,1,4661.643,H021192,3.43
4,4,5,0,0,NaN,NaN,NaN,NaN,NaN,2,...,NaN,NaN,1,1,1,10,1,10929.554,H025576,1.27

In [11]:
cols = ['ANXEV_A', 'AGEP_A', 'SEX_A', 'RACEALLP_A', 'HISP_A', 'URBRRL', 'REGION', 'EDUCP_A', 'MLTFAMFLG_A', 'PCNTADLT_A', 'PCTKIDS_A', 'OVER65FLG_A', 'EDUCP_A', 'MARSTAR_A', 'CITZNSTP_A']

df = df[cols].copy()

KeyError: "['PCTKIDS_A', 'MARSTAR_A'] not in index"

In [12]:
cols = ['ANXEV_A', 'AGEP_A', 'SEX_A', 'RACEALLP_A', 'HISP_A', 'URBRRL', 'REGION', 'EDUCP_A', 'MLTFAMFLG_A', 'PCNTADLT_A', 'PCNTKIDS_A', 'OVER65FLG_A', 'MARSTAT_A', 'CITZNSTP_A']

df = df[cols].copy()

In [13]:
print(df.shape)

(29522, 14)

In [14]:
df.head()

,ANXEV_A,AGEP_A,SEX_A,RACEALLP_A,HISP_A,URBRRL,REGION,EDUCP_A,MLTFAMFLG_A,PCNTADLT_A,PCNTKIDS_A,OVER65FLG_A,MARSTAT_A,CITZNSTP_A
0,2,67,1,2,2,3,3,1,2,2,0,1,8,1
1,2,73,1,1,2,4,3,8,2,1,0,1,6,1
2,2,48,1,2,2,4,3,5,2,2,2,0,1,1
3,2,42,2,1,2,4,3,9,2,2,3,0,1,1
4,2,50,2,1,2,4,3,7,2,2,1,0,5,1

In [15]:
missing_report = df.isnull().sum()

In [16]:
missing_report = missing_report[missing_report >0]

In [17]:
print("Columns with missing values:")
print(missing_report)

Columns with missing values:
Series([], dtype: int64)

In [1]:
#replacement of null-values with excluding Marital Status and Educational Level

import numpy as np

exclude_cols = ['EDUCP_A', 'MARSTAT_A']

invalid_values = [7, 8, 9, 97, 98, 99]

#excepting Marital Status
cols_to_clean = [col for col in df.columns if col not in exclude_cols]

df[cols_to_clean] = df[cols_to_clean].replace(invalid_values, np.nan)

NameError: name 'df' is not defined